@Library("jenlib") _

try {
    stage("Cleanup") {
        runOnSlave(label: "frontend") {
            cleanWs()
        }
    }

    stage("Checkout") {
        runOnSlave(label: "frontend") {
            checkout scm
        }
    }
    stage("Flake8 check") {
        runOnSlave(label: "frontend") {
            inSingularity(app: "visionary-dev-tools") {
                jesh "flake8 --tee --output flake8.log"
            }
            step([$class: 'WarningsPublisher',
                  parserConfigurations: [[parserName: 'Pep8',
                                          pattern: 'flake8.log']],
                  unstableTotalAll: '0',
                  usePreviousBuildAsReference: true
                ])
        }
    }
    stage("Build") {
        onSlurmResource(partition: "jenkins") {
            inSingularity(app: "visionary-simulation") {
                jesh "bash -x .ci/stages/build.sh"
            }
        }
    }
    stage("Analyze log") {
        runOnSlave(label: "frontend") {
            warnings canComputeNew: false,
                     canRunOnFailed: true,
                     consoleParsers: [[parserName: 'GNU C Compiler 4 (gcc)']],
                     excludePattern: '.*npy_1_7_deprecated_api.h$',
                     unstableTotalAll: '0'
        }
    }
    stage("Build model-visionary-nest") {
        runOnSlave(label: "frontend") {
            inSingularity(app: "visionary-simulation") {
                jesh "bash -x .ci/stages/visionary-nest-checkout.sh"
            }
        }
        onSlurmResource(partition: "jenkins") {
            inSingularity(app: "visionary-simulation") {
                jesh "cd model-visionary-nest && bash -x .ci/stages/build.sh"
            }
        }
    }
    stage("Run tests") {
        onSlurmResource(partition: "jenkins") {
            inSingularity(app: "visionary-dev-tools") {
                jesh "bash -x .ci/stages/test.sh"
                archiveArtifacts("tests/*.png")
                step([$class: 'XUnitBuilder',
                      thresholds: [[$class: 'FailedThreshold', unstableThreshold:'0']],
                      tools: [[$class: 'JUnitType', pattern: 'tests/test_results.xml']]])
            }
        }
    }
} finally {
    runOnSlave(label: "frontend") {
        cleanWs()
    }
}
